- name: Configure hosts & deploy application
  hosts: app
  become: true
  vars:
    db_host: "62.84.127.125:27017"
  tasks:
    - name:  daemon_reload
      systemd: daemon_reload=true

    - name: Add unit file for Puma
      copy:
        src: files/puma.service
        dest: /etc/systemd/system/puma.service
      notify: reload puma
    - name: enable puma
      systemd: name=puma daemon_reload=true enabled=yes
    - name: Add config for DB connection
      template:
        src: templates/db_config.j2
        dest: /home/ubuntu/db_config
  handlers:
    - name: reload puma
      systemd: name=puma state=restarted
